--sistema de banco de dados para integração com java no projeto FacilitaReabi


DROP TABLE consulta CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE paciente CASCADE CONSTRAINTS;

DROP SEQUENCE paciente_seq;
DROP SEQUENCE usuario_seq;
DROP SEQUENCE consulta_seq;


CREATE TABLE paciente(
    id_paciente NUMBER(4) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL, 
    cpf VARCHAR2(12) NOT NULL,
    dataNascimento DATE NOT NULL,
    telefone VARCHAR2(20) NOT NULL,
    email VARCHAR2(40) NOT NULL,
    vulnerabilidade VARCHAR2(150) NOT NULL,
    aptidao VARCHAR2(20) NOT NULL
);

CREATE TABLE usuario(
    id NUMBER(4) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR2(20) NOT NULL,
    senha VARCHAR2(12) NOT NULL,
    feedback VARCHAR2(200) NULL
);

CREATE TABLE consulta(
    id NUMBER(4) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataConsulta DATE NOT NULL,
    statusConsulta VARCHAR2(15) NOT NULL,
    motivoFalta VARCHAR2(100),
    especializacao VARCHAR2(30) NOT NULL,
    id_paciente NUMBER NOT NULL,
    CONSTRAINT fk_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id_paciente)
);

CREATE SEQUENCE paciente_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE usuario_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE consulta_seq START WITH 1 INCREMENT BY 1;


SELECT * FROM paciente;
SELECT * FROM usuario;
SELECT * FROM consulta;

